### ISSUE TITLE
期待作者更新

### ISSUE THREAD

**Issue by jianqiao0313** [332557712/cc#1]
看了你写的项目，学习很多，好多写法好简洁~
期待更新~

**Comment by jianqiao0313** [comment]
对了  confirm模态框要是想自定义确定事件 取消事件如何实现？

**Comment by 332557712** [comment]
@jianqiao0313 

你不用自己定义事件，想要拿到点击确定按钮的结果可通过result来获得，这个组件是基于ng-bootstrap的modal做的，你可以参考https://ng-bootstrap.github.io/#/components/modal

**Comment by 332557712** [comment]
@jianqiao0313 
有时间都会加东西进来的
