### ISSUE TITLE
"instanceof" 表达式左侧必须是 "any" 类型、对象类型或类型参数。

### ISSUE THREAD

**Issue by lisztj** [332557712/cc#15]
ERROR in G:/node/cc/node_modules/ng2-img-cropper/src/exif.ts (709,38): The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter.
我把img的类型设置成any就可以正常构建成功了！
![tim 20171027093716](https://user-images.githubusercontent.com/14845217/32084261-9fdb0860-bafa-11e7-9618-0d51b4783d93.png)

**Comment by 332557712** [comment]
@lisztj 你直接改里面的源代码了？

**Comment by lisztj** [comment]
@332557712 是啊，不然一直构建不成功，报这个错误

**Comment by 332557712** [comment]
@lisztj  最好不要这样，万一升级了麻烦，是不是可以考虑集成后重写，或是告诉那个原作者，让他改

**Comment by lisztj** [comment]
@332557712 好的
