### ISSUE TITLE
赞作者

### ISSUE THREAD

**Issue by EricVicky** [332557712/cc#17]
使用不同的前端技术实现同一种框架,作者很牛鼻,完全是小公司做小项目的福利,有着一个框架,改一改格式,可以适应不同的项目需求.节省了不少成本......

**Comment by 332557712** [comment]
@EricVicky  更让你意外的是，我还是一个后端开发

**Comment by EricVicky** [comment]
奥,怪不得起个名字叫后台管理系统登陆!!话说这个系统里的各种控件,插件,你都是怎样找的?平日工作遇到的觉得不错的就托进来?还是?吸取下精盐~~~

**Comment by 332557712** [comment]
@EricVicky 感觉有用的就网上找一个，没有的或是不好用的就自己写一个

**Comment by EricVicky** [comment]
非常好啊,以前做项目都用angularjs,现在换成Angular了有些地方还真是不是很习惯,公司需要我的前后端也都要开发,希望以后可以多多向你讨教!!!Thanks~

**Comment by 332557712** [comment]
@EricVicky 有1的基础加是后端基础上手很快的，基本上3天就可以上手了

**Comment by EricVicky** [comment]
还好,现在正在用你的前端cc做一个SSM架构的小feature,嘿嘿~

**Comment by 332557712** [comment]
@EricVicky 我是准备用spring boot搞

**Comment by zzzhan** [comment]
真的太好，赞一下。我能不能在这里说请教一个angular 的问题？
在angularjs2的教程里(https://angular.io/tutorial/toh-pt6#error-handling)，下面这句在ATOM编辑器中一直报错，是什么问题？rxjs版本问题还是？

*import { catchError, map, tap } from 'rxjs/operators"*

**Comment by 332557712** [comment]
@zzzhan 这个我还真不清楚，我也遇到过

**Comment by zzzhan** [comment]
谢谢！有没有什么地方可以问的？stackoverflow又上不去，中文社区注册了也收不到验证邮件-_-!!!

**Comment by 332557712** [comment]
@zzzhan 研究下，试一下，跟踪一下

**Comment by zzzhan** [comment]
试了很久了，确实解决不了呀。感觉rxjs版本问题，angular的例子真是坑呀

**Comment by zzzhan** [comment]
真的是，在你项目下更新就一下版本就好了
建议升级一下项目的angular 相关版本:)

*npm update rxjs*

**Comment by 332557712** [comment]
@ @zzzhan 用yarn更新吧
