### ISSUE TITLE
toast组件的用法

### ISSUE THREAD

**Issue by EricVicky** [332557712/cc#18]
你好,我想问下toast组件的用法,比如说login成功后怎样触发toast弹出的?谢谢.

**Comment by 332557712** [comment]
**1.引入toast的服务**
    import { ToastService } from '../shared/toast/toast.service';
**2.引入toast的类型与配置类**
   import { ToastConfig, ToastType } from '../shared/toast/toast-model';
**3.在构造方法中注入服务**
   constructor(private toastService: ToastService)
**4.实例化一个toast配置，第一个参数为类型，第二个参数为粗体字，第三个参数为正常字体，第四个参数为多久关闭，最后通过服务显示**
  const toastCfg = new ToastConfig(ToastType.SUCCESS, '', '百变小咖，登录成功!', 2000);
  this.toastService.toast(toastCfg);
**5.具体使用可以通过登录、组件示例**
