### ISSUE TITLE
使用ng build --prod 的时候报错

### ISSUE THREAD

**Issue by CodingYiyi** [332557712/cc#2]
类似的全是这种错误，使用ng serve 或者 ng build --dev 都是OK的
ERROR in /Users/XXX/Desktop/Angular2App/cc-master/src/$$_gendir/app/home/home.component.ngfactory.ts (579
,35): Property 'userTipClose' does not exist on type 'HomeComponent'.

ERROR in ng:///Users/XXX/Desktop/Angular2App/cc-master/src/app/home/home.component.html (32,29): Property
 'todoObj' is private and only accessible within class 'HomeComponent'.

ERROR in ng:///Users/XXX/Desktop/Angular2App/cc-master/src/app/home/home.component.html (79,29): Property
 'noticeObj' is private and only accessible within class 'HomeComponent'.

**Comment by 332557712** [comment]
@CodingYiyi 用npm start
